### ISSUE TITLE
When I run gradle idea it prompts error

### ISSUE THREAD

**Issue by wizardbyron** [dave-ellis/gradle-swagger-plugin#2]
FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/twer/projects/gradle-swagger-plugin/build.gradle' line: 40
- What went wrong:
  A problem occurred evaluating root project 'gradle-swagger-plugin'.
  
  > Could not find property 'compile' on root project 'gradle-swagger-plugin'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by TriPhoenix** [comment]
For those who may stumble over this as well: looks like the build script has been build pre-gradle-2.0 so you need a gradle up to 1.12 (checked with 1.9 and 1.12, breaks with gradle 2.0) to use this. gradle-wrapper can be an alternative to achieve this, although you might encounter issues later on when mixing with post-2.0 gradle code.
